name: devopsfrnt
version: 1.0.0+1
description: "Application Flutter DevOps"

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.29.2"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/shutterstock_721758364.png