FROM cirrusci/flutter:stable AS build
RUN flutter upgrade
WORKDIR /app
COPY . .
RUN flutter pub get
RUN flutter build web
FROM nginx:alpine
COPY --from=build /app/build/web /usr/share/nginx/html
EXPOSE 80
